name: Pull Request Workflow

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Fetch git branches
      run: |
        git fetch
        git checkout main
        git checkout ${{ github.sha }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm i -g lerna
    - name: Install dependencies of changed packages
      run: lerna bootstrap --since main --hoist
    - name: Build changed packages
      run: lerna run build --since main
    - name: Run Tests in changed packages
      run: lerna run test --since main



